### ISSUE TITLE
unclear sentence

### ISSUE THREAD

**Issue by cbeny** [tobiasosborne/What-is-a-quantum-field-state-#1]
I do not quite understand the meaning of this sentence:

"This approach is easier to implement numerically, and also more directly allows the computation of, e.g., quantum entanglement, but it does throw up the intriguing question of concretely understanding how a discretised TNS has anything to do with a given continuous QFT".

It sounds like the second part just contradicts the first..

**Comment by tobiasosborne** [comment]
This sentence has been rewritten (the contradictory bit at the end removed).
